config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  ###################################
  root to: 'public/homes#top'


  # 会員側のルーティング設定
  ## URLの「public」部分なしのができる！
  scope module: :public do
    ## 取得できるアクションがメジャーなやつだけなのでイレギュラーのアクションは「GET」で指定する必要がある！
    get '/about' => 'homes#about'
    ## URLが違うものになるものは「get」などで一つずつ指定してあげる！

    # 「customers」
    get '/customers/my_page' => 'customers#show', as: 'my_page'
    get '/customers/information/edit' => 'customers#edit', as: 'customers_edit'
    patch '/customers/information' => 'customers#update', as: 'information'
    get '/customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'

    # 「Cart_items」
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'

    # 「Orders」
    post '/orders/confirm' => 'orders#confirm', as: 'confirm'
    get '/orders/complete' => 'orders#complete', as: 'complete'

    resources :items, :cart_items, :orders, :addresses
  end
  #####################
  # 管理者側のルーティング設定
  ## URLの頭に「admin」入れる設定
  namespace :admin do
    root to: 'homes#top'
    resources :items, :customers, :genres, :orders, :order_details

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image

  validates :name, :introduction, :price, presence: true
  validates :price, numericality: { only_integer: true }

  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  belongs_to :genre

  ## 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end
    ## 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end

  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!

  def new
    @item = Item.new

  end

  def create
    @item = Item.new(item_params)
      # binding.pry
    if @item.save
    # 投稿成功した場合
    flash[:notice]="登録完了しました！"
    redirect_to admin_item_path(@item.id)
    else
    # 投稿が失敗した場合
    @items=Item.all
    render :index
    end
  end

  def index
    # @items = Item.all
    @items = Item.all.page(params[:page]).per(10)
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])

  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
    # 更新に成功したときの処理
      flash[:notice]="更新完了しました！"
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end


  private
  def genre_params
    params.require(:genre).permit(:name)
  end
  def item_params
    params.require(:item).permit(:name, :item_image, :introduction, :price, :is_active, :genre_id)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h5 class="bg-light d-inline px-4 ml-5">商品編集</h5>
    </div>

  </div>

  <div class="row mt-4">
    <div class="col-md-8 mx-auto">
        <%= form_with model: @item, url: admin_item_path(@item.id) do |f| %>

        <div class="field d-md-flex mt-3">
          <div class="col-md-3">
            <%= f.label :'商品画像'%>
          </div>
          <div class="col-md-6">
          <%= f.file_field :item_image, placeholder: "", accept: "image/*" %>
          </div>
        </div>

        <div class="field d-md-flex mt-3">
          <div class="col-md-3">
          <%= f.label :'商品名'%>
          </div>
          <div class="col-md-6">
          <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "商品名", class: "form-control " %>
          </div>
        </div>

        <div class="field d-md-flex mt-3">
          <div class="col-md-3">
          <%= f.label :'商品説明'%>
          </div>
          <div class="col-md-6">
          <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder: "ここに説明文を記述します", class:'form-control' %>
          </div>
        </div>

        <div class="field d-md-flex mt-3">
          <div class="col-md-3">
          <%= f.label :'ジャンル'%>
          </div>
          <div class="col-md-6 d-flex">
            <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい"  %>
          </div>
        </div>

        <div class="field d-md-flex mt-3">
          <div class="col-md-3">
          <%= f.label :'税抜価格'%>
          </div>
          <div class="col-md-6 d-flex">
          <%= f.text_field :price, autofocus: true, id:"inputPrice", placeholder: "1000", class:'form-control' %>
          <p>円</p>
          </div>
        </div>

        <div class="field d-md-flex mt-3">
          <div class="col-md-3">
          <%= f.label :'販売ステータス'%>
          </div>
          <div class="col-md-6">
            <label>
              <%= f.radio_button :is_active, true %>販売中
            </label>
            <label class="ml-3">
              <%= f.radio_button :is_active, false %>販売停止
            </label>
            </div>
        </div>



      <div class="mx-auto d-flex justify-content-center">
      <button type="submit" class="btn btn-success my-4 mx-auto px-4">
        変更を保存
      </button>

      </div>
      <% end %>


    </div>
  </div>




</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 d-flex mx-auto">
      <div class="mr-auto">
        <h5 class="d-inline bg-light px-4 text-center">商品一覧</h5>
      </div>
      <div>
        <%= link_to new_admin_item_path, class: 'text-dark' do %>
        <i class="fa-regular fa-square-plus fa-2x"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-11 mx-auto">
      <table class="table table-borderless mt-4 border-bottom border-top">
        <thead class="bg-light">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
        </thead>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admin_item_path(item.id) %></td>
          <td><%= item.price.to_s(:delimited) %></td>
          <td><%= item.genre.name %></td>

          <%if item.is_active %>
          <td class="text-success">
          <b>販売中</b>
          </td>
          <% else %>
          <td class="text-secondary">
          販売停止中
          </td>
          <% end %>
        </tr>
        <% end %>
      </table>
    </div>
    <div class="mx-auto"><%= paginate @items %></div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h5 class="bg-light d-inline px-4 ml-5">商品新規登録</h5>
    </div>

  </div>

  <div class="row mt-4">
    <div class="col-md-8 mx-auto">
        <%= form_with model: @item, url: admin_items_path do |f| %>

        <div class="field d-md-flex mt-3">
          <div class="col-md-3">
            <%= f.label :'商品画像'%>
          </div>
          <div class="col-md-6">
          <%= f.file_field :item_image, placeholder: "", accept: "image/*" %>
          </div>
        </div>

        <div class="field d-md-flex mt-3">
          <div class="col-md-3">
          <%= f.label :'商品名'%>
          </div>
          <div class="col-md-6">
          <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "商品名", class: "form-control " %>
          </div>
        </div>

        <div class="field d-md-flex mt-3">
          <div class="col-md-3">
          <%= f.label :'商品説明'%>
          </div>
          <div class="col-md-6">
          <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder: "ここに説明文を記述します", class:'form-control' %>
          </div>
        </div>

        <div class="field d-md-flex mt-3">
          <div class="col-md-3">
          <%= f.label :'ジャンル'%>
          </div>
          <div class="col-md-6 d-flex">
            <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい"  %>
          </div>
        </div>

        <div class="field d-md-flex mt-3">
          <div class="col-md-3">
          <%= f.label :'税抜価格'%>
          </div>
          <div class="col-md-6 d-flex">
          <%= f.text_field :price, autofocus: true, id:"inputPrice", placeholder: "1000", class:'form-control' %>
          <p>円</p>
          </div>
        </div>

        <div class="field d-md-flex mt-3">
          <div class="col-md-3">
          <%= f.label :'販売ステータス'%>
          </div>
          <div class="col-md-6">
            <label>
              <%= f.radio_button :is_active, true, checked: true %>販売中
            </label>
            <label class="ml-3">
              <%= f.radio_button :is_active, false %>販売停止
            </label>
            </div>
        </div>



      <div class="mx-auto d-flex justify-content-center">
      <button type="submit" class="btn btn-success my-4 mx-auto px-4">
        新規登録
      </button>

      </div>
      <% end %>


    </div>
  </div>




</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <h5 class="d-inline bg-light px-4">商品詳細</h5>
    </div>
  </div>

  <div class="row mt-4">
    <!--商品画像-->
    <div class="col-md-4">
      <%= image_tag @item.item_image,size: '300x200', url: admin_item_path %>
    </div>

    <div class="col-lg-8">

      <table class="table-sm">
        <tr>
          <td>商品名</td>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <td>税込価格<br>(税抜価格)</td>
          <td><%= @item.with_tax_price.to_s(:delimited) %>（<%= @item.price.to_s(:delimited) %>）<span>円</span></td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <%if @item.is_active %>
          <td class="text-success">販売中</td>
          <% else %>
          <td class="text-secondary">販売停止中</td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6"></div>
    <div class="col-md-3">
      <%= link_to '編集する', edit_admin_item_path, class: 'btn btn-success px-4 mt-4' %>
    </div>

  </div>

        </div>
      </div>
    </div>
  </div>
</div>