config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  ###################################
  root to: 'public/homes#top'


  # 会員側のルーティング設定
  ## URLの「public」部分なしのができる！
  scope module: :public do
    ## 取得できるアクションがメジャーなやつだけなのでイレギュラーのアクションは「GET」で指定する必要がある！
    get '/about' => 'homes#about'
    ## URLが違うものになるものは「get」などで一つずつ指定してあげる！

    # 「customers」
    get '/customers/my_page' => 'customers#show', as: 'my_page'
    get '/customers/information/edit' => 'customers#edit', as: 'customers_edit'
    patch '/customers/information' => 'customers#update', as: 'information'
    get '/customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'

    # 「Cart_items」
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'

    # 「Orders」
    post '/orders/confirm' => 'orders#confirm', as: 'confirm'
    get '/orders/complete' => 'orders#complete', as: 'complete'

    resources :items, :cart_items, :orders, :addresses
  end
  #####################
  # 管理者側のルーティング設定
  ## URLの頭に「admin」入れる設定
  namespace :admin do
    root to: 'homes#top'
    resources :items, :customers, :genres, :orders, :order_details

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, presence: true
  # validates :is_deleted, inclusion:{in: [true, false]}
  validates :last_name_kana, :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: "is invalid. Input full-width katakana characters." }


  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def full_name
    self.last_name + " " + self.first_name
  end
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + full_name
  end
  def address_display_nameless
    '〒' + postal_code + ' ' + address
  end
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    # @customers = Customer.all
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
    # 更新に成功したときの処理
      flash[:notice]="更新完了しました！"
      redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end



  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">

  <%= form_with model: @customer ,url: admin_customer_path(@customer.id) do |f| %>
  <h5 class="bg-light d-inline px-2"><%= @customer.full_name %>さんの会員情報編集</h5>

  <div class="row mt-4">
    <div class="col-md-12 m-auto">

      <div class="field d-flex my-2">
        <div class="col-md-3">
          <p>会員ID</p>
        </div>
        <div class="col-md-3">
          <%= @customer.id %>
        </div>
      </div>

      <!--氏名-->
      <div class="field d-md-flex my-2">
        <div class="col-md-3">
          <%= f.label :'氏名' %>
        </div>
        <div class="col-md-3 mb-2">
          <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", placeholder: "令和", class: "form-control " %>
        </div>
        <div class="col-md-3 mb-2">
          <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", placeholder: "道子", class: "form-control " %>
        </div>
      </div>
      <!--フリガナ-->
      <div class="field d-md-flex my-2">
        <div class="col-md-3">
          <%= f.label :'フリガナ' %>
        </div>

        <div class="col-md-3 mb-2">
          <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana", class: "form-control" %>
        </div>

        <div class="col-md-3 mb-2">
          <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana", class: "form-control" %>
        </div>
      </div>

      <!--郵便番号-->
      <div class="field d-md-flex my-2">
        <div class="col-md-3">
          <%= f.label :'郵便番号'%>
        </div>
        <div class="col-md-3 mb-2">
          <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", class: "form-control " %>
        </div>
      </div>

      <!--住所-->
      <div class="field d-md-flex my-2">
        <div class="col-md-3">
          <%= f.label :'住所'%>
        </div>
        <div class="col-md-6 mb-2">
          <%= f.text_field :address, autofocus: true, autocomplete: "address", class: "form-control " %>
        </div>
      </div>

      <!--電話番号-->
      <div class="field d-md-flex my-2">
        <div class="col-md-3">
          <%= f.label :'電話番号'%>
        </div>
        <div class="col-md-3 mb-2">
          <%= f.telephone_field :telephone_number, autofocus: true, autocomplete: "telephone_number", class: "form-control " %>
        </div>
      </div>

      <!--メールアドレス-->
      <div class="field d-md-flex my-2">
        <div class="col-md-3">
          <%= f.label :メールアドレス %>
        </div>
        <div class="col-md-3 mb-2">
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
        </div>
      </div>

      <!--会員ステータス-->
      <div class="field d-md-flex">
        <div class="col-md-3">
          <%= f.label :'会員ステータス'%>
        </div>
        <div class="col-md-6">
          <label>
            <%= f.radio_button :is_deleted, false %>有効
          </label>
          <label class="ml-3">
            <%= f.radio_button :is_deleted, true %>退会
          </label>
        </div>
      </div>

      <div class="actions">
        <div class="col-md-6 mx-auto">
          <button type="submit" class="btn btn-success my-4 mx-auto p-auto">
            変更を保存
          </button>
        </div>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5">
      <h5 class="bg-light px-4 d-inline ml-md-5">会員一覧</h5>
    </div>
  </div>

  <div class="row">
    <div class="col-md-10 mx-auto">
      <table class="table mt-4">
        <thead class="bg-light">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
        </thead>
        <% @customers.each do |customer| %>

        <tr class="border-bottom">
          <td><%= customer.id %></td>
          <td><%= link_to customer.full_name, admin_customer_path(customer.id) %></td>
          <td><%= customer.email %></td>
          <%if customer.is_deleted %>
          <td class="text-secondary">
            退会
          </td>
          <% else %>
          <td class="text-success">
            有効
          </td>
          <% end %>
        </tr>
        <% end %>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto"><%= paginate @customers %></div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <h5 class="bg-light px-4 d-inline ml-md-3"><%= @customer.full_name %>さんの会員詳細</h5>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-6">
      <table class="table table-borderless">
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @customer.full_name %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= @customer.full_name_kana %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= @customer.telephone_number %></td>
        </tr>

        <tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>

        <tr>
          <td>会員ステータス</td>
          <td>
            <%if @customer.is_deleted %>
            <p class="text-secondary"><b>退会</b></p>
            <% else %>
            <p class="text-success"><b>有効</b></p>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3"></div>
      <div class="col-md-2 mt-2">
        <%= link_to '編集する', edit_admin_customer_path, class: 'btn btn-success' %>
      </div>

      <div class="col-md-4 mt-2">
        <%= link_to '注文履歴一覧を見る', admin_order_path(@customer.id), class: 'btn btn-primary ' %>
      </div>
    </div>
  </div>
</div>