config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  ###################################
  root to: 'public/homes#top'


  # 会員側のルーティング設定
  ## URLの「public」部分なしのができる！
  scope module: :public do
    ## 取得できるアクションがメジャーなやつだけなのでイレギュラーのアクションは「GET」で指定する必要がある！
    get '/about' => 'homes#about'
    ## URLが違うものになるものは「get」などで一つずつ指定してあげる！

    # 「customers」
    get '/customers/my_page' => 'customers#show', as: 'my_page'
    get '/customers/information/edit' => 'customers#edit', as: 'customers_edit'
    patch '/customers/information' => 'customers#update', as: 'information'
    get '/customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'

    # 「Cart_items」
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'

    # 「Orders」
    post '/orders/confirm' => 'orders#confirm', as: 'confirm'
    get '/orders/complete' => 'orders#complete', as: 'complete'

    resources :items, :cart_items, :orders, :addresses
  end
  #####################
  # 管理者側のルーティング設定
  ## URLの頭に「admin」入れる設定
  namespace :admin do
    root to: 'homes#top'
    resources :items, :customers, :genres, :orders, :order_details

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
  has_many :items, dependent: :destroy
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all

  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
    # 投稿成功した場合
    flash[:notice]="作成完了しました！"
    redirect_to admin_genres_path
    else
    # 投稿が失敗した場合
    @genres=Genre.all
    render :index
    end

  end

  def edit
     @genre = Genre.find(params[:id])
    # @book = Book.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      # 更新に成功したときの処理
      flash[:notice]="更新完了しました！"
      redirect_to admin_genres_path
    else
      render 'edit'
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
  def item_params
    params.require(:item).permit(:name, :item_image, :introduction, :price, :is_active)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <h5 class="d-inline px-4 bg-light">ジャンル編集</h5>
      </div>
    </div>

    <div class="row mt-5">
      <%= form_with model: @genre, url: admin_genre_path(@genre.id) do |f| %>
      <div class="d-md-flex">
        <div class="mb-2">
          <%= f.label :'ジャンル名'%>
        </div>
        <div class="ml-md-4 mb-3">
          <%= f.text_field :name, autofocus: true, class: "form-control" %>
        </div>
        <div class="ml-md-3 mb-3">
          <%= f.submit "変更を保存",class: "btn btn-success" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/admin/genres/index.html.erb
<!--ジャンル一覧・追加ページ-->
<div class="container">
  <div class="row">
    <h5 class="bg-light d-inline px-4 ml-5">ジャンル一覧・追加</h5>
  </div>

  <div class="row mt-5">
  <!--ジャンル登録-->
    <%= form_with model: @genre, url: admin_genres_path do |f| %>
    <div class="col-md-12 d-md-flex">
      <div class="col-md-3">
        <%= f.label :'ジャンル名'%>
      </div>

      <div class="col-md-7">
        <%=f.text_field:name, placeholder: "ジャンル名", class: 'form-control mb-3' %>
      </div>

      <div class="col-md-4">
        <button type="submit" class="btn btn-success mb-3">新規登録</button>
      </div>
    </div>
    <% end %>
  </div>

  <!--ジャンル編集-->
  <div class="row">
    <div class="col-md-7">
      <table class="table mb-3">
        <thead class="bg-light">
        <tr>
          <th class="px-5">ジャンル</th>
          <th></th>
        </tr>
        </thead>
        <% @genres.each do |genre| %>
        <tr class="border-bottom my-auto">
          <td><%= genre.name %></td>
          <td>
            <%= link_to '編集する', edit_admin_genre_path(genre.id), class: 'btn btn-success' %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>

</div>