config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  ###################################
  root to: 'public/homes#top'


  # 会員側のルーティング設定
  ## URLの「public」部分なしのができる！
  scope module: :public do
    ## 取得できるアクションがメジャーなやつだけなのでイレギュラーのアクションは「GET」で指定する必要がある！
    get '/about' => 'homes#about'
    ## URLが違うものになるものは「get」などで一つずつ指定してあげる！

    # 「customers」
    get '/customers/my_page' => 'customers#show', as: 'my_page'
    get '/customers/information/edit' => 'customers#edit', as: 'customers_edit'
    patch '/customers/information' => 'customers#update', as: 'information'
    get '/customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'

    # 「Cart_items」
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'

    # 「Orders」
    post '/orders/confirm' => 'orders#confirm', as: 'confirm'
    get '/orders/complete' => 'orders#complete', as: 'complete'

    resources :items, :cart_items, :orders, :addresses
  end
  #####################
  # 管理者側のルーティング設定
  ## URLの頭に「admin」入れる設定
  namespace :admin do
    root to: 'homes#top'
    resources :items, :customers, :genres, :orders, :order_details

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  validates :postal_code,:address,:name, presence: true

  belongs_to :customer
  
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, :encrypted_password, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  validates :amount, presence: true

  belongs_to :customer
  belongs_to :item


  def subtotal
    item.with_tax_price * amount
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, presence: true
  # validates :is_deleted, inclusion:{in: [true, false]}
  validates :last_name_kana, :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: "is invalid. Input full-width katakana characters." }


  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def full_name
    self.last_name + " " + self.first_name
  end
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + full_name
  end
  def address_display_nameless
    '〒' + postal_code + ' ' + address
  end
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image

  validates :name, :introduction, :price, presence: true
  validates :price, numericality: { only_integer: true }

  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  belongs_to :genre

  ## 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end
    ## 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end

  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end


end

app/models/order.rb
class Order < ApplicationRecord
  validates :postal_code, :address, :name, :postage, :total_price, presence: true

  has_many :order_details
  belongs_to :customer
  has_many :items, through: :order_details

  enum order_status:{
    payment_wating: 0, #入金待ち
    payment_confirmation: 1, #入金確認
    in_product: 2, #製作中
    preparing_delivery: 3, #発送準備中
    delivered: 4 #発送済み
  }
  enum payment:{
    credit_card: 0, #クレジットカード
    bank: 1 #銀行振込
  }
  def full_name
    self.last_name + " " + self.first_name
  end
  def address_display_nameless
    '〒' + postal_code + ' ' + address
  end
  ## 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end
  ## 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  validates :price, :amount, presence: true

  belongs_to :order
  belongs_to :item

  enum production_status:{
    start_not_possible: 0, #着手不可
    production_pending: 1, #製作待ち
    in_production: 2, #製作中
    production_end: 3 #製作終了
  }

    ## 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end
  ## 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end
  def full_name
    self.last_name + " " + self.first_name
  end
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + full_name
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!

  def top
    # @orders = Order.all
    # @order = Order.find(params[:id])
    # @order_details = OrderDetail.all
    # @order_detail = OrderDetail.find(params[:id])
    ## ページネーションへ記述変更
    @orders = Order.all.page(params[:page]).per(10)


  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :postage, :total_price, :order_status, :payment, :customer_id, :address_id)
  end
  def order_detail_params
    params.require(:order_detail).permit(:price, :amount, :production_status,:item_id, :order_id)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!

  def new
    @item = Item.new

  end

  def create
    @item = Item.new(item_params)
      # binding.pry
    if @item.save
    # 投稿成功した場合
    flash[:notice]="登録完了しました！"
    redirect_to admin_item_path(@item.id)
    else
    # 投稿が失敗した場合
    @items=Item.all
    render :index
    end
  end

  def index
    # @items = Item.all
    @items = Item.all.page(params[:page]).per(10)
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])

  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
    # 更新に成功したときの処理
      flash[:notice]="更新完了しました！"
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end


  private
  def genre_params
    params.require(:genre).permit(:name)
  end
  def item_params
    params.require(:item).permit(:name, :item_image, :introduction, :price, :is_active, :genre_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # before_action :configure_permitted_parameters, if: :devise_controller?
  # def top
  #   @customer = Customer.find(customer_params)
  # end
  # private
  # def customer_params
  #   params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_deleted)
  # end
  def search
    #Viewのformで取得したパラメータをモデルに渡す
    @items = Item.search(params[:search])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_flash_window.html.erb
<div class="flash-window hidden text-success mb-3">
  <%= flash[:notice] %>
</div>
<div class="flash-window hidden text-danger mb-3">
  <%= flash[:error] %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/c1c2279c79.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <!--ヘッダーここから-->
    <header class="bg-light text-secondary shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-1 text-dark" href="/"><strong>ながのCAKE</strong></a>
          <!--レスポンシブボタン-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <!--レスポンシブボタンここまで-->
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <!--ナビゲーション-->
            <ul class="navbar-nav ml-auto">

            <!--カスタマーログイン-->
            <% if customer_signed_in? %>
            <div>
              <div class="d-lg-flex">
              <li class="nav-item">
                <p class="text-left mt-2 mr-md-5 text-success">ようこそ、<%= current_customer.last_name %>さん!</p>
              </li>

              <!--マイページ-->
              <li class="nav-item">
                <%= link_to 'マイページ', my_page_path, class: 'nav-link btn btn-outline-secondary mr-md-2 my-1' %>
              </li>
              <!--商品一覧-->
              <li class="nav-item">
                <%= link_to '商品一覧', items_path, class: 'nav-link btn btn-outline-secondary mr-md-2 my-1' %>
              </li>
              <!--カート-->
              <li class="nav-item">
              <%= link_to 'カート', cart_items_path, class: 'nav-link btn btn-outline-secondary mr-md-2 my-1' %>
              </li>
              <!--ログアウト-->
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link btn btn-outline-secondary my-1' %>
              </li>
              </div>

              <div class="search_form text-right">
                <%= form_tag(items_path, :method => "get") do %>
                <%= text_field_tag :search %>
                <%= submit_tag "検索" ,:item => nil ,class: "button is-info"%>
                <% end %>
              </div>
            </div>
            <% elsif admin_signed_in? %>
              <!--管理者ログイン-->
              <!--商品一覧-->
            <div>
              <div class="d-lg-flex">
                <li class="nav-item">
                  <%= link_to '商品一覧', admin_items_path, class: 'nav-link btn btn-outline-secondary mr-md-2  my-1' %>
                </li>
                <!--会員一覧-->
                <li class="nav-item">
                <%= link_to '会員一覧', admin_customers_path, class: 'nav-link btn btn-outline-secondary mr-md-2 my-1' %>
                </li>
                <!--注文履歴一覧-->
                <li class="nav-item">
                <%= link_to '注文履歴一覧', admin_root_path, class: 'nav-link btn btn-outline-secondary mr-md-2 my-1' %>
                </li>
                <!--ジャンル一覧-->
                <li class="nav-item">
                <%= link_to 'ジャンル一覧', admin_genres_path, class: 'nav-link btn btn-outline-secondary mr-md-2 my-1' %>
                </li>
                <!--ログアウト-->
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link btn btn-outline-secondary mr-md-2 my-1' %>
                </li>
              </div>

              <div class="search_form text-right">
                <%= form_tag(items_path, :method => "get") do %>
                <%= text_field_tag :search %>
                <%= submit_tag "検索" ,:item => nil ,class: "button is-info"%>
                <% end %>
              </div>
            </div>

              <% else %>
              <!--未ログインユーザー-->
              <!--アバウト-->
            <div>
              <div class="d-lg-flex">
                <li class="nav-item">
                <%= link_to 'About',about_path, class: 'nav-link btn btn-outline-secondary mr-md-2 my-1' %>
              </li>
              <!--商品一覧-->
              <li class="nav-item">
                <%= link_to '商品一覧',items_path, class: 'nav-link btn btn-outline-secondary mr-md-2 my-1' %>
              </li>
              <!--新規登録-->
              <li class="nav-item">
                <%= link_to '新規登録' ,new_customer_registration_path, class: 'nav-link btn btn-outline-secondary mr-md-2 my-1' %>
              </li>
              <!--ログイン-->
              <li class="nav-item">
                <% if request.fullpath.include? "/admin" %>
                  <!--admin側のheaderを返す-->
                  <%= link_to 'ログイン', new_admin_session_path, class: 'nav-link btn btn-outline-secondary mr-md-2 my-1' %>
                  <% else %>
                  <!--user側のheaderを返す-->
                  <%= link_to 'ログイン', new_customer_session_path, class: 'nav-link btn btn-outline-secondary my-1' %>
                <% end %>
              </li>
              </div>

              <div class="search_form text-right">
                <%= form_tag(items_path, :method => "get") do %>
                <%= text_field_tag :search %>
                <%= submit_tag "検索" ,:item => nil ,class: "button is-info"%>
                <% end %>
              </div>
              <% end %>
            </div>

            </ul>
            </div>

            <!--<div class="search_form">-->
            <!--  <%#= form_tag(items_path, :method => "get") do %>-->
            <!--  <%#= text_field_tag :search %>-->
            <!--  <%#= submit_tag "検索" ,:item => nil ,class: "button is-info"%>-->
            <!--  <%# end %>-->
            <!--</div>-->


          </div>
        </div>
      </nav>
    </header>
    <main class="m-4 mb-5">
    <%= render partial: 'layouts/flash_window' %>
    <%= yield %>
    </main>
    <footer>
      <div class="bg-secondary text-secondary py-4 fixed-bottom"></div>
    </footer>
  </body>
</html>